version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgras_taks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taks_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: taks_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taks_db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - .:/app
    
volumes:
  db_data:
  